destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/IMPS-pdf"
port: 4011
output: pdf
product: IMPS
print_title: IMPS documentation
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: imps_sidebar
