destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/ArrowPoint-pdf"
port: 4010
output: pdf
product: ArrowPoint
print_title: Documentation — ArrowPoint product
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: arrowpoint_sidebar
